mkdir int-01-post/coords
mkdir int-02-post/coords
mkdir int-03-post/coords
mkdir int-04-post/coords
mkdir int-05-post/coords
mkdir int-06-post/coords
mkdir int-07-post/coords
mkdir int-08-post/coords
mkdir int-09-post/coords
mkdir int-10-post/coords
mkdir int-11-post/coords
mkdir int-12-post/coords
mkdir int-tip-post/coords
mkdir pside-post/coords
mkdir sside-post/coords
mkdir tip-post/coords
mkdir trail-post/coords
mkdir lead-post/coords