mkdir int-01-post/coords
mkdir int-01-post/rms
mkdir int-01-post/fft
mkdir int-02-post/coords
mkdir int-02-post/rms
mkdir int-02-post/fft
mkdir int-03-post/coords
mkdir int-03-post/rms
mkdir int-03-post/fft
mkdir int-04-post/coords
mkdir int-04-post/rms
mkdir int-04-post/fft
mkdir int-05-post/coords
mkdir int-05-post/rms
mkdir int-05-post/fft
mkdir int-06-post/coords
mkdir int-06-post/rms
mkdir int-06-post/fft
mkdir int-07-post/coords
mkdir int-07-post/rms
mkdir int-07-post/fft
mkdir int-08-post/coords
mkdir int-08-post/rms
mkdir int-08-post/fft
mkdir int-09-post/coords
mkdir int-09-post/rms
mkdir int-09-post/fft
mkdir int-10-post/coords
mkdir int-10-post/rms
mkdir int-10-post/fft
mkdir int-11-post/coords
mkdir int-11-post/rms
mkdir int-11-post/fft
mkdir int-12-post/coords
mkdir int-12-post/rms
mkdir int-12-post/fft
mkdir int-tip-post/coords
mkdir int-tip-post/rms
mkdir int-tip-post/fft
mkdir pside-post/coords
mkdir pside-post/rms
mkdir pside-post/fft
mkdir sside-post/coords
mkdir sside-post/rms
mkdir sside-post/fft
mkdir tip-post/coords
mkdir tip-post/rms
mkdir tip-post/fft
mkdir trail-post/coords
mkdir trail-post/rms
mkdir trail-post/fft
mkdir lead-post/coords
mkdir lead-post/rms
mkdir lead-post/fft